title: What's The Weather Like?
email: info@whatstheweatherlike.io
description: >- 
  This site aims to provide immediate information about the current weather
  to the user at his location with minimal interaction while being as
  fast and accurate as possible.
baseurl: ""
url: "https://www.whatstheweatherlike.io"
twitter_username:
github_username:  whatstheweatherlike
weather_service_url: "https://weather-service-lb-582828591.eu-central-1.elb.amazonaws.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

